### ISSUE TITLE
Requires an update for the newest version of SteamUI

### ISSUE THREAD

**Issue by lividhen** [cboiangiu/decky-dictation#2]
When loading the plugin it fails to init. I think your base is outdated. Also, are you planning to work on this still? It's a really cool project.

**Comment by cboiangiu** [comment]
I do plan on finally making a successful release of this soon enough.

**Comment by bjorn1500** [comment]
i am also waiting on this one. would be really great to have.

**Comment by Slvrtnge** [comment]
Hope this gets updated someday would be very helpful!

**Comment by cboiangiu** [comment]
@Slvrtnge An update is available in the testing store as the plugin moves through the release pipeline: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/576
There does seem to be a bug with decky itself, which we'll have to deal with before releasing to prod. (try to reinstall it a couple times, it should install eventually)
