### ISSUE TITLE
Fix double dictation bug and add push to talk option

### ISSUE THREAD

**Issue by cboiangiu** [cboiangiu/decky-dictation#9]
Found a bug while trying this out that triggers a double dictation:

1. Inside a game (FF14 in my case) enable the plugin from the toggle
2. Inside a text box press L5
3. A second after the notification appears informing the dictation has started press L5
4. Say "one"
5. See "11" or similar double-dictation printed out.

Probably not a deal breaker for an early version as it does work with this in mind but reporting so you know. 

_Originally posted by @grimkor in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/576#issuecomment-2203022295_

**Comment by grimkor** [comment]
Hey @cboiangiu I have a branch that has this fixed as well as a push-to-talk option. Are you accepting PRs and if so how would you like it?
